Blogger/Controllers/AdminPanelPostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blogger.Models;
using Microsoft.AspNet.Identity;

namespace Blogger.Controllers
{
    public class AdminPanelPostController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AdminPanelPost
        public ActionResult Index()
        {
            var postDetails = db.PostDetails.Include(p => p.CategoryDetail);
            return View(postDetails.ToList());
        }

        // GET: AdminPanelPost/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PostDetail postDetail = db.PostDetails.Find(id);
            if (postDetail == null)
            {
                return HttpNotFound();
            }
            return View(postDetail);
        }

        // GET: AdminPanelPost/Create
        public ActionResult Create()
        {
            PostDetail model = new PostDetail();
           
            model.CategoryDetails = db.Categories;
            return View(model);
        }

        // POST: AdminPanelPost/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create( PostDetail postDetail)
        {
            if (ModelState.IsValid)
            {
               
                if (postDetail.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(postDetail.ImageUpload.FileName);
                    string extension = Path.GetExtension(postDetail.ImageUpload.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    postDetail.FeaturedImage = "~/Content/Images/" + fileName;
                    postDetail.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/Images/"), fileName));
                }
                postDetail.Create_time = DateTime.Now;
                db.PostDetails.Add(postDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
           

                
               

                ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", postDetail.CategoryId);
            return View(postDetail);
        }

        // GET: AdminPanelPost/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PostDetail postDetail = db.PostDetails.Find(id);
            if (postDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", postDetail.CategoryId);
            return View(postDetail);
        }

        // POST: AdminPanelPost/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PostId,Title,Post_Content,Create_time,Tages,FeaturedImage,CategoryId,UserId")] PostDetail postDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(postDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", postDetail.CategoryId);
            return View(postDetail);
        }

        // GET: AdminPanelPost/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PostDetail postDetail = db.PostDetails.Find(id);
            if (postDetail == null)
            {
                return HttpNotFound();
            }
            return View(postDetail);
        }

        // POST: AdminPanelPost/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PostDetail postDetail = db.PostDetails.Find(id);
            db.PostDetails.Remove(postDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Blogger/Views/AdminPanelPost/Create.cshtml
@model Blogger.Models.PostDetail
@{
    ViewBag.Title = "NewPost";

}

@*<script src="~/Theme/ckeditor.js"></script>*@

<div class="container body-content-pages">
    <h2> New Post</h2>

    @using (Html.BeginForm("Create", "AdminPanelPost", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data", onSubmit = "return JQueryAjaxPost(this);" }))
    {


        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.HiddenFor(model => model.PostId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.PostId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PostId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.FeaturedImage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <img src="@Url.Content(Model.FeaturedImage)" height="100" width="100" id="imagePreview" />
                    <input type="file" name="ImageUpload" accept="image/jpg,image/png" onchange="ShowImagePreview(this, document.getElementById('imagePreview'))" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12 input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </span>
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "Title" } })
                </div>
                <div>
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    @Html.TextAreaFor(model => model.Post_Content, new { id = "summernote", name = "editordata" })
                    @Html.ValidationMessageFor(model => model.Post_Content, "", new { @class = "text-danger" })
                </div>
            </div>
            @*<script>

                CKEDITOR.replace("ckeditor");
            </script>*@
            <div class="form-group">
                <div class="col-md-12">
                    @Html.LabelFor(model => model.Tages, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Tages, new { htmlAttributes = new { @class = "form-control", data_role = "tagsinput", placeholder = "Add tags" } })
                    @Html.ValidationMessageFor(model => model.Tages, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.CategoryId, new SelectList(Model.CategoryDetails, "CategoryId", "CategoryName"))
                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12 input-group">
                    <button type="submit" class="btn btn-primary" aria-label="Left Align">
                        <span class="fa fa fa-pencil-square-o" aria-hidden="true"> </span> Publish
                    </button>
                </div>
            </div>
        </div>
    }
</div>
@section Scripts {
  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>

<!-- include summernote css/js -->
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
<script>
    $(document).ready(function() {
        $('#summernote').summernote({
            placeholder: 'Type here...',
            width : 650,
        tabsize: 2,
        height: 100
    });
});
</script>
}

Blogger/Views/AdminPanelPost/Delete.cshtml
@model Blogger.Models.PostDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PostDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryDetail.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryDetail.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Create_time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Create_time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tages)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FeaturedImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FeaturedImage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Blogger/Views/AdminPanelPost/Details.cshtml
@model Blogger.Models.PostDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PostDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryDetail.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryDetail.CategoryName)
        </dd>


       
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Create_time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Create_time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tages)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FeaturedImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FeaturedImage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PostId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Blogger/Views/AdminPanelPost/Edit.cshtml
@model Blogger.Models.PostDetail

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.PostId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.PostId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FeaturedImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content(Model.FeaturedImage)" height="100" width="100" id="imagePreview" />
                <input type="file" name="ImageUpload" accept="image/jpg,image/png" onchange="ShowImagePreview(this, document.getElementById('imagePreview'))" />
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-12 input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-pencil"></span>
                </span>
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "Title" } })
            </div>
            <div>
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                @Html.TextAreaFor(model => model.Post_Content, new { @id = "ckeditor" })
                @Html.ValidationMessageFor(model => model.Post_Content, "", new { @class = "text-danger" })
            </div>
        </div>
        <script>

                CKEDITOR.replace("ckeditor");
        </script>
        <div class="form-group">
            <div class="col-md-12">
                @Html.LabelFor(model => model.Tages, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Tages, new { htmlAttributes = new { @class = "form-control", data_role = "tagsinput", placeholder = "Add tags" } })
                @Html.ValidationMessageFor(model => model.Tages, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label" })
                @Html.DropDownListFor(model => model.CategoryId, new SelectList(Model.CategoryDetails, "CategoryId", "CategoryName"))
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 input-group">
                <button type="submit" class="btn btn-primary" aria-label="Left Align">
                    <span class="fa fa fa-pencil-square-o" aria-hidden="true"> </span> Publish
                </button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blogger/Views/AdminPanelPost/Index.cshtml
@model IEnumerable<Blogger.Models.PostDetail>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Category Name")
        </th>
       
        <th>
            @Html.DisplayName("Title")
        </th>
      
        <th>
            @Html.DisplayName("Date")
        </th>
      
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryDetail.CategoryName)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.Create_time)
        </td>
       
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PostId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PostId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PostId })
        </td>
    </tr>
}

</table>